# Generated by Django 4.2.6 on 2023-10-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackings',
            options={'verbose_name': 'Tracking'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='workouts',
            options={'verbose_name': 'Workout'},
        ),
        migrations.AlterModelTable(
            name='trackings',
            table='Tracking',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterModelTable(
            name='workouts',
            table='Workout',
        ),
    ]
