# Generated by Django 4.2.6 on 2023-10-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0005_alter_friends_user_alter_friends_userfriend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercise',
            old_name='excercise',
            new_name='exercise',
        ),
    ]
