# Generated by Django 4.2.6 on 2023-10-18 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0007_excercise_sets_alter_excercise_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackings',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackings',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
