# Generated by Django 4.2.6 on 2023-10-18 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0008_trackings_started_trackings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackings',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='fit.workouts'),
        ),
    ]
