# Generated by Django 4.2.6 on 2023-11-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_alter_trackings_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackings',
            name='time',
            field=models.DateField(auto_created=True),
        ),
    ]
