# Generated by Django 4.2.6 on 2023-11-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0013_friends_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='accepted',
        ),
        migrations.AddField(
            model_name='friends',
            name='requeststatus',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('REJ', 'Rejected'), ('PEN', 'Pending')], default=('PEN', 'Pending'), max_length=20),
        ),
    ]
