# Generated by Django 4.2.6 on 2023-11-22 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0015_friends_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='category',
            field=models.CharField(choices=[('CARDIO', 'Cardio'), ('WORKOUT', 'Workout')], default='workout', max_length=30),
        ),
        migrations.AlterField(
            model_name='friends',
            name='requeststatus',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('REJ', 'Rejected'), ('PEN', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='userfriend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
