# Generated by Django 4.2.6 on 2023-11-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0016_workouts_category_alter_friends_requeststatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='category',
            field=models.CharField(choices=[('CARDIO', 'Cardio'), ('WORKOUT', 'Workout')], default='WORKOUT', max_length=30),
        ),
    ]
